using System.Globalization;
using System.Text;

namespace TrestleBoard.Screenshots;

/// <summary>
/// Writes <c>docs/images/README.md</c>: one row per image saying what it shows, how it was made,
/// and when. Generated rather than hand-kept, because a hand-kept index of eighteen images is an
/// index that silently goes wrong.
///
/// It also carries the two <b>reserved</b> filenames — the SmartScreen and Gatekeeper install
/// shots, which are operating-system dialogs no harness can render and which M10 still lists as
/// open. They are named here so they have a home and a documented standard, but deliberately
/// written WITHOUT an <c>![…]</c> line: the documentation gate fails on a referenced image that
/// does not exist, and it should.
/// </summary>
internal static class ImageIndex
{
    private static readonly (string Name, string What)[] Reserved =
    [
        ("install-smartscreen",
            "Windows SmartScreen's \"More info → Run anyway\" step, referenced by docs/INSTALL.md."),
        ("install-gatekeeper",
            "macOS Gatekeeper's right-click → Open step, referenced by docs/INSTALL.md."),
    ];

    public static void Write(string directory, IReadOnlyList<Shot> shots, DateOnly generatedOn)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(directory);
        ArgumentNullException.ThrowIfNull(shots);

        var text = new StringBuilder();
        text.AppendLine("# Images in the documentation");
        text.AppendLine();
        text.AppendLine("Every image in this folder is generated by `tools/TrestleBoard.Screenshots`");
        text.AppendLine("against the fictional sample issue and fictional roster fixtures, in a");
        text.AppendLine("temporary app-state root. The harness cannot read `%AppData%/TrestleBoard`, so it");
        text.AppendLine("cannot load the real address book or a real recovery snapshot (PLAN.md §0 rule 6).");
        text.AppendLine();
        text.AppendLine("Regenerate all of them:");
        text.AppendLine();
        text.AppendLine("```");
        text.AppendLine("dotnet run --project tools/TrestleBoard.Screenshots");
        text.AppendLine("```");
        text.AppendLine();
        text.AppendLine("or just the ones that moved, which is the usual case — PNGs do not delta, so every");
        text.AppendLine("regeneration adds a full copy to the repository's history:");
        text.AppendLine();
        text.AppendLine("```");
        text.AppendLine("dotnet run --project tools/TrestleBoard.Screenshots -- --only font-picker");
        text.AppendLine("```");
        text.AppendLine();
        text.AppendLine(CultureInfo.InvariantCulture, $"Last regenerated: **{generatedOn:yyyy-MM-dd}**, TrestleBoard **{Version()}**.");
        text.AppendLine("That date covers the run that last touched this file; a `--only` run rewrites it");
        text.AppendLine("while leaving the other images as they were, which is the honest reading of it.");
        text.AppendLine();
        text.AppendLine("## The images");
        text.AppendLine();

        foreach (Shot shot in shots)
        {
            text.AppendLine(CultureInfo.InvariantCulture, $"### `{shot.Name}.png`");
            text.AppendLine();
            text.AppendLine(CultureInfo.InvariantCulture, $"{shot.Caption} ({Describe(shot.Kind)})");
            text.AppendLine();
            text.AppendLine(CultureInfo.InvariantCulture,
                $"`dotnet run --project tools/TrestleBoard.Screenshots -- --only {shot.Name}`");
            text.AppendLine();
            text.AppendLine(CultureInfo.InvariantCulture, $"![{shot.AltText}]({shot.Name}.png)");
            text.AppendLine();
        }

        text.AppendLine("## Reserved, hand-taken, not yet captured");
        text.AppendLine();
        text.AppendLine("These two are operating-system security dialogs. No harness can render them, and");
        text.AppendLine("M10 still carries them as open acceptance items. They must show no personal data");
        text.AppendLine("and no path bearing a user name. **Do not add an image link for either until the");
        text.AppendLine("file exists** — `DocsTests` fails on a referenced image that is not there.");
        text.AppendLine();

        foreach ((string name, string what) in Reserved)
        {
            text.AppendLine(CultureInfo.InvariantCulture, $"- `{name}.png` — {what} Hand-taken, not yet captured.");
        }

        File.WriteAllText(Path.Combine(directory, "README.md"), text.ToString());
    }

    private static string Describe(ShotKind kind) => kind switch
    {
        ShotKind.Window => "the whole editor window, 1280×860, Light, 100% scale",
        ShotKind.Dialog => "one dialog on its own",
        _ => "drawn by the rendering engine — no Avalonia involved",
    };

    private static string Version() =>
        typeof(TrestleBoard.App.MainWindow).Assembly.GetName().Version?.ToString(3) ?? "unknown";
}
